baseURL = "https://bilal-bhatti.github.io/"
languageCode = "en-us"
title = "Bilal Bhatti"
theme = "hugo-primer"
copyright = "&copy;Bilal Bhatti 2019"

[params]
# Chose Social Sharing Buttons you want to use.
shareTo = ["Twitter"]
# You may disable copyright sentence by setting this to false.
showFooterCredits = true
description = "Describe what your web page is about"
twitter = "bilalwala"
# You can use favicon by addin them manually.
useIcon = true
useTwitterCard = true
summaryLength = 25

[frontmatter]
# update sitemap.xml's lastmod datetime by file change time, instead of git.
# lastmod = ["lastmod", ":fileModTime", ":default"]
